CREATE TABLE `lojas` (
	`codigo` VARCHAR(50) NULL DEFAULT NULL,
	`nome` VARCHAR(100) NULL DEFAULT NULL,
	`lat` VARCHAR(200) NULL DEFAULT NULL,
	`lon` VARCHAR(200) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
